const sidebars = {
  sidebar: [
  {
			type: 'category',
			label: 'Documentation',
			collapsed: true,
			items: [
				{
					type: 'autogenerated',
					dirName: 'Documentation'
				}
			]
		}
  ],
};

module.exports = sidebars;
